version: '3.8'

services:

  front:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    ports:
      - 81:80
    depends_on:
      api:
        condition: service_started

  api:
    image: Andrew-715/taskplanner:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file: .env
    restart: always
    environment:
      DATABASE_HOST: db
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./core:/app/core
      - ./TaskPlanner:/app/TaskPlanner

  migrations:
    image: Andrew-715/taskplanner:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - 8111:8000
    command: >
      sh -c "python ./manage.py migrate"

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - TaskPlanner_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}
      timeout: 3s
      interval: 4s
      retries: 10

volumes:
  TaskPlanner_data:
