name: Build and deploy

on:
  push:
    branches-ignore:
      - master
      - develop
      - HW34

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: docker build
        uses: docker build -t Andrew-715/taskplanner:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker push
        run: docker push Andrew-715/taskplanner:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: render configs
        run: |
          mkdir deploy_ci
          cat docker-compose-ci.yaml | envsubst > deploy_ci/docker-compose.yaml
          cat .env | envsubst > deploy_ci/.env
      - name: Copy on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "deploy_ci/docker-compose.yaml,deploy_ci/.env"
          target: "TaskPlanner"
          strip_components: 1
      - name: Run compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd TaskPlanner
            docker-compose down
            docker-compose up -d
